AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  coin-game-lambda-sam-app

  Sample SAM Template for coin-game-lambda-sam-app

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    Architectures:
      - x86_64
    LoggingConfig:
      LogFormat: JSON

Resources:
  SetUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: set_user_function.set_user_handler
      Environment:
        Variables:
          DYNAMODB_TABLE: "coin_game_user_table"

  GetUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: get_user_function.get_user_handler
      Environment:
        Variables:
          DYNAMODB_TABLE: "coin_game_user_table"

  GetaffiliationListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: get_affiliation_list_function.get_affiliation_list_handler
      Environment:
        Variables:
          DYNAMODB_TABLE: "coin_game_user_table"

  SetDeeplearningResultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: set_deeplearning_result_function.set_deeplearning_result_handler
      Environment:
        Variables:
          DYNAMODB_TABLE: "upbit_deeplearning_table"

  GetDeeplearningResultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: get_deeplearning_result_function.get_deeplearning_result_handler
      Environment:
        Variables:
          DYNAMODB_TABLE: "upbit_deeplearning_table"

  GetTheBestUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: get_the_best_user_function.get_the_best_user_handler
      Environment:
        Variables:
          DYNAMODB_TABLE: "coin_game_user_table"

  SetClickStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: set_click_stream_function.set_click_stream_handler
      Environment:
        Variables:
          KINESIS_STREAM_NAME: "coin-game-kinesis"
          FIREHOSE_STREAM_NAME: "ClickStream-PUT-S3"
  
  KDStoS3ParquetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: KDS_to_S3_parquet_function.KDS_to_S3_parquet_handler
      Environment:
        Variables:
          RAW_DATA_BUCKET: "aws-s3-bucket-fastcampus"
          RAW_DATA_PREFIX: "ClickStream/raw-data/"

  KDFS3ParquetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: KDF_S3_parquet_function.KDF_S3_parquet_handler

  getUserAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: get_user_analysis_function.get_user_analysis_handler
      Environment:
        Variables:
          BUCKET_NAME: "aws-s3-bucket-fastcampus"
          PREFIX: "ClickStream/analytics_results/"

  websocketConnetcionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: websocket_connection_function.websocket_connection_handler
      Environment:
        Variables:
          CONNECTIONS_TABLE: websocket_connections

  websocketDisconnetcionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: websocket_disconnection_function.websocket_disconnection_handler
      Environment:
        Variables:
          CONNECTIONS_TABLE: websocket_connections

  websocketDefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: coin_sam_code/
      Handler: websocket_default_function.websocket_default_handler
      Environment:
        Variables:
          DATA_TABLE: dynamoDB_upbit_table
          CONNECTIONS_TABLE: websocket_connections

Outputs:
  SetUserDataFunction:
    Description: ARN of the SetUserData Lambda Function
    Value: !GetAtt SetUserDataFunction.Arn

  SetUserDataFunctionIamRole:
    Description: IAM Role for SetUserDataFunction
    Value: !GetAtt SetUserDataFunctionRole.Arn

  KinesisStreamName:
    Description: Name of the Kinesis Stream
    Value: coin-game-kinesis
